config/routes.rb
BooksKreatio::Application.routes.draw do
  get "books/new"
  get "books/about"
  get "books/boks"
  get "books/category"
  get "books/my_account"
  get "books/contact"
  get "books/find"
  post "uploads/uploadFile"

  root :to => "books#new"

  post "books/create"
end

app/models/book.rb
class Book < ActiveRecord::Base
  searchable do
    text :title
    text :image
  end 
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/store_book.rb
class StoreBook < ActiveRecord::Base
 def self.save(upload, r_ip)
    name =  upload.original_filename
    directory = "#{Rails.root}/public/data/"
    path = File.join(directory, name)
    img = "#{upload.original_filename.split(" ").join("-")}-size90.png"
    File.open(path, "wb") { |f| f.write(upload.read) }
    Book.create(title: name, file: "/data/#{name}", upload_date: Date.today, created_by: r_ip, image: "/digital_assets/images/#{img}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def new
  
  end
  
  

def find
 @search = Book.search do
    fulltext params[:search]
  end
  @books = @search.results   
end

  
  
  def create
   @contact=Contact.new(books_params)
       if @contact.save
          redirect_to books_contact_url
          flash[:notice] = "Contact saved successfully"
        else
          render "new"
        end 
  end


def serve
  path = "/public/data/#{params[:filename]}"

  send_file( path,
  :disposition => 'inline',
  :type => 'application/pdf',
  :x_sendfile => true )
end 




  def about
    
  end
  
  def boks
    @books = Book.order("updated_at DESC").paginate(:page => params[:page], :per_page => 7)
  end
  
  def category
    
  end
  
  def myaccount
    
  end
  
  def contact
    
  end
  
  private
  
  def books_params
    params.require(:books).permit(:id, :name, :email, :phone, :message)
  end
  
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def index
    render :file => 'app\views\uploads\uploadfile.rhtml'
  end

  def uploadfile
    post = StoreBook.save(params[:dafile], request.remote_ip)

    Grim.reap(params[:dafile].path)
    a = Grim.reap(params[:dafile].path)
    params[:dafile].original_filename
    jpg = a[0].save("#{Rails.root}/public/digital_assets/images/#{params[:dafile].original_filename.gsub(/\s/,'-')}.png")
    `convert #{Rails.root}/public/digital_assets/images/#{params[:dafile].original_filename.gsub(/\s/,'-')}.png -resize 90 #{Rails.root}/public/digital_assets/images/#{params[:dafile].original_filename.gsub(/\s/,'-')}-size90.png`

    render :text => "File has been uploaded successfully"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def link_to_book(b_id)
    b = Book.find(b_id).display_name
    "/data/#{b}"
  end
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/books/about.html.erb
<div class="center_content">
	<div class="left_content">
		<div class="title">
			<span class="title_icon"> <img src="/assets/bullet1.gif" alt="" title="" /></span>About us
		</div>

		<div class="feat_prod_box_details">
			<p class="details">
				<img src="/assets/about.gif" alt="" title="" class="right" />
			<p>
				BookStore.net is a super quick and simple search engine for books that
				helps you find the price and availability of books across various online
				bookstores. It also provides user store reviews, which further help users
				to choose the best deal on the right store.
				The BookStore.net blog Bookish is _the_ destination for bibliophiles.
				It provides users book reviews, author interviews, articles by published authors,
				book releases, information on literary events, interesting articles that trigger your
				nerves to think and more.

				BookStore.net will hopefully help you find your book, and save some money to top it off. :)

				We are small and growing, your feedback is highly appreciated.

				Follow us on <a href="http://www.facebook.com">Facebook</a> or <a href="http://www.twitter.com">Twitter</a>.
			</p>
		</div>
		<div class="clear"></div>
	</div>
</div>

app/views/books/boks.html.erb
<div class="center_content">
	<div class="left_content">

		<div class="title">
			<span class="title_icon"><img src="/assets/bullet1.gif" alt="" title="" /> </span>Books 
		</div>

		<% @books.each do |book|%>
		<div class="feat_prod_box">

			<div class="prod_img">

				<img src="<%= book.image%>" alt="" title="" border="0" /></a>
			</div>

			<div class="prod_det_box">
				<span class="special_icon"> </span>
				<div class="box_top"></div>
				<div class="box_center">
					<div class="prod_title">
						<%= book.title%></a>
					</div>
					<p class="details">
						Uploaded Date: <%= book.upload_date.to_datetime.strftime("%a, %B %d %Y")%>
					</p>

					<div class="clear"></div>
				</div>

				<div class="box_bottom"></div>
			</div>
			<div class="clear"></div>
		</div>
		<% end %>
		<%= will_paginate @books %>
		

		<div class="clear"></div>
	</div>

</div>

app/views/books/category.html.erb
<div class="center_content">
	<div class="left_content">
		<div class="title">
				<span class="title_icon"> <img title="" alt="" src="/assets/bullet1.gif"></img> </span>
				Catageory
		</div>

		<div class="new_products">

			<div class="new_prod_box">

				<a href="">Ruby Language</a>

				<div class="new_prod_bg">

					<img src="/assets/ii.jpg" alt="" title="" class="thumb" border="0" />
					</a>
				</div>
			</div>

			<div class="new_prod_box">

				<a href="">Learn to Program</a>

				<div class="new_prod_bg">
					<span class="new_icon"> <img src="/assets/new_icon.gif" alt="" title="" /></span>

					<img src="/assets/h.jpg" alt="" title="" class="thumb" border="0" />
					</a>
				</div>
			</div>

			<div class="new_prod_box">

				<a href="">Ruby Tutorials</a>
				<div class="new_prod_bg">
					<span class="new_icon"> <img src="/assets/promo_icon.gif" alt="" title="" /></span>

					<img src="/assets/oh.jpg" alt="" title="" class="thumb" border="0" />
					</a>
				</div>
			</div>

			<div class="title">
				<span class="title_icon"><img src="/assets/bullet2.gif" alt="" title="" /> </span><abbr title="Cascading Style Sheet" class="initialism"><a href="">CSS</a></abbr>
			</div>

			<div class="new_products">
				<div class="new_prod_box">
					<a href="">Beginning CSS</a>
					<div class="new_prod_bg">

						<img src="/assets/gth.jpg" alt="" title="" class="thumb" border="0" />
						</a>
					</div>
				</div>

				<div class="new_prod_box">
					<a href="">The Book of CSS 3</a>
					<div class="new_prod_bg">
						<span class="new_icon"> <img src="/assets/promo_icon.gif" alt="" title="" /></span>

						<img src="/assets/sc.jpg" alt="" title="" class="thumb" border="0" />
						</a>
					</div>
				</div>

				<div class="new_prod_box">
					<a href="">Complete CSS</a>
					<div class="new_prod_bg">

						<img src="/assets/d.jpg" alt="" title="" class="thumb" border="0" />
						</a>
					</div>
				</div>
			</div>

			<div class="title">
				<span class="title_icon"><img src="/assets/bullet2.gif" alt="" title="" /> </span>
				<a href="">JavaScript</a>
			</div>

			<div class="new_products">

				<div class="new_prod_box">
					<a href="">JS for web Developers</a>
					<div class="new_prod_bg">
						<span class="new_icon"> <img src="/assets/new_icon.gif" alt="" title="" /></span>

						<img src="/assets/jaa.jpg" alt="" title="" class="thumb" border="0" />
						</a>
					</div>
				</div>

				<div class="new_prod_box">
					<a href="">The Complete reference</a>
					<div class="new_prod_bg">

						<img src="/assets/d.jpg" alt="" title="" class="tkrhumb" border="0" />
						</a>
					</div>
				</div>

				<div class="new_prod_box">
					<a href="">JS for web Apps</a>
					<div class="new_prod_bg">

						<img src="/assets/pr.jpg" alt="" title="" class="thumb" border="0" />
						</a>
					</div>
				</div>

			</div>

			<div class="title">
				<span class="title_icon"><img src="/assets/bullet2.gif" alt="" title="" /> </span><abbr title="HyperText Markup Language" class="initialism"><a href="">HTML</a></abbr>
			</div>

			<div class="new_products">

				<div class="new_prod_box">
					<a href="">Head first HTML</a>
					<div class="new_prod_bg">
						<span class="new_icon"> <img src="/assets/new_icon.gif" alt="" title="" /></span>

						<img src="/assets/hhk.jpg" alt="" title="" class="thumb" border="0" />
						</a>
					</div>
				</div>
				<div class="new_prod_box">
					<a href="">HTML 5 Dummles</a>
					<div class="new_prod_bg">

						<img src="/assets/lll.png" alt="" title="" class="thumb" border="0" />
						</a>
					</div>
				</div>

				<div class="new_prod_box">
					<a href="">The Complete Reference</a>
					<div class="new_prod_bg">

						<img src="/assets/uk.jpg" alt="" title="" class="thumb" border="0" />
						</a>
					</div>
				</div>

			</div>
		</div>

		<div class="clear"></div>
	</div>
</div>

app/views/books/contact.html.erb
 <div class="center_content">
       	<div class="left_content">
            <div class="title">
            	<span class="title_icon">
            		<img src="/assets/icon_contact.gif" alt="" title="" /></span>Contact Us
            		
            		</div>
       
        	<div class="feat_prod_box_details">
            <p class="details">
            
 
I would love to hear on how you like/dislike BookStore.net. Mail me on 
<a href="http://www.kreatio.com">feedback@bookstore.net</a> or submit this small form.
 Ideas and suggestions are welcome. </p>
            
              	<div class="contact_form">
                <div class="form_subtitle">All fields are requierd</div> 
    
<% flash.each do |key, value| %>
		<div class="alert-show"><%= value %></div>
			   <% end %>
 <%= form_tag books_create_url do %>
  <p>
    <%= label_tag :name %><br />
    <%= text_field_tag "books[name]" %>
  </p>
       <p>
    <%= label_tag :email %><br />
    <%= text_field_tag "books[email]" %>
  </p>
  <p>
    <%= label_tag :phone %><br />
    <%= text_field_tag "books[phone]" %>
  </p>
 
  <p>
    <%= label_tag :message %><br />
    <textarea name="books[message]" style="height: 55px; width: 230px;"></textarea>
 
  </p>
  
      <%= submit_tag("Send")%> <br />
    
    <% end %> 
               
</div>  
   </div>
 <div class="clear"></div>
        </div>
 
 
    </div>
    
    
    
    
    
       

app/views/books/find.html.erb
<h1>You searched for : <%= params[:search]%></h1>

<% @books.each do |book|%>
<div class="feat_prod_box">

	<div class="prod_img">

		<img src="<%= book.image%>" alt="" title="" border="0" /></a>
	</div>

	<div class="prod_det_box">
		<span class="special_icon"> </span>
		<div class="box_top"></div>
		<div class="box_center">
			<div class="prod_title">
				<%= book.title%></a>
			</div>
			<p class="details">
				Uploaded Date: <%= book.upload_date.to_datetime.strftime("%a, %B %d %Y")%>
			</p>

			<div class="clear"></div>
		</div>

		<div class="box_bottom"></div>
	</div>
	<div class="clear"></div>
</div>
<% end %>
<%= will_paginate @books %>

app/views/books/home.html.erb
<div class="center_content">

	<div class="left_content">

		<div class="title">
			<span class="title_icon"> <img src="/assets/bullet1.gif" alt="" title="" /> </span>
			<%= link_to "Most Downloaded", books_category_path%>

		</div>

		<div class="feat_prod_box">

			<div class="prod_img">
				<p>
					<img src="/assets/rrr.jpg" alt="" title="click to more details" border="0" />
				</p>
			</div>

			<div class="prod_det_box">
				<div class="box_top"></div>
				<div class="box_center">
					<div class="prod_title">
						<a href='<%= Book.find(4).file%>' target="_blank" >The Book of Ruby</a>
					</div>
					<p class="details">
						In this book, it is my aim to guide you safely
						over the pitfalls and lead you
						through the choppy waters of Ruby’s syntax and class libraries.
						In the process, I’ll be exploring both the smooth, well-paved highways
						and the gnarlier,bumpy little byways of Ruby.
					</p>

					<div class="clear"></div>
				</div>

				<div class="box_bottom"></div>
			</div>
			<div class="clear"></div>
		</div>

		<div class="feat_prod_box">

			<div class="prod_img">
				<p>
					<img src="/assets/cs.jpg" alt="" title="click to more details" border="0" />
				</p>
			</div>

			<div class="prod_det_box">
				<div class="box_top"></div>
				<div class="box_center">
					<div class="prod_title">
						<a href='<%= Book.find(5).file%>' target="_blank" >The Book of CSS 3</a>
					</div>
					<p class="details">
						The Book of CSS3 helps you leverage the
						excellent knowledge you have of
						CSS2.1 in order to make learning CSS3 easier.

					</p>

					<div class="clear"></div>
				</div>
				<div class="box_bottom"></div>
			</div>
			<div class="clear"></div>
		</div>

		<div class="title">
			<span class="title_icon"> <img src="/assets/bullet2.gif" alt="" title="" /> </span><%= link_to "Most Recent", books_boks_path %>
		</div>

		<div class="new_products">

			<div class="new_prod_box">
				<a href='<%= Book.find(6).file%>' target="_blank" >Web development</a>

				<div class="new_prod_bg">
					<span class="new_icon"> <img src="/assets/new_icon.gif" alt="" title="" /></span>
					<img src="/assets/al.jpg" alt="" title="" class="thumb" border="0" />
				</div>
			</div>

			<div class="new_prod_box">
				<a href='<%= Book.find(18).file%>' target="_blank" >Beginning CSS</a>
				<div class="new_prod_bg">
					<span class="new_icon"> <img src="/assets/new_icon.gif" alt="" title="" /></span>
					<img src="/assets/gth.jpg" alt="" title="" class="thumb" border="0" /> </a>
				</div>
			</div>

			<div class="new_prod_box">
				<a href='<%= Book.find(7).file%>' target="_blank" >JS for web Developers</a>
				<div class="new_prod_bg">
					<span class="new_icon"> <img src="/assets/new_icon.gif" alt="" title="" /></span>
					<img src="/assets/jaa.jpg" alt="" title="" class="thumb" border="0" /> </a>
				</div>
			</div>

			<div class="new_prod_box">
				<a href='<%= Book.find(19).file%>' target="_blank" >Ruby on Rails 3</a>
				<div class="new_prod_bg">
					<span class="new_icon"> <img src="/assets/new_icon.gif" alt="" title="" /></span>
					<img src="/assets/oh.jpg" alt="" title="" class="thumb" border="0" /> </a>
				</div>
			</div>

			<div class="new_prod_box">
				<a href='<%= Book.find(20).file%>' target="_blank" >JS for web Apps</a>
				<div class="new_prod_bg">
					<span class="new_icon"> <img src="/assets/new_icon.gif" alt="" title="" /></span>
					<img src="/assets/pr.jpg" alt="" title="" class="thumb" border="0" /> </a>
				</div>
			</div>

			<div class="new_prod_box">
				<a href='<%= Book.find(21).file%>' target="_blank" >The Complete reference</a>
				<div class="new_prod_bg">
					<span class="new_icon"> <img src="/assets/new_icon.gif" alt="" title="" /></span>
					<img src="/assets/uk.jpg" alt="" title="" class="thumb" border="0" /> </a>
				</div>

			</div>

		</div>

		<div class="clear"></div>
	</div>

</div>

app/views/books/my_account.html.erb
<div class="center_content">
	<div class="left_content">
		<%= form_tag '/uploads/uploadFile', :multipart => true do %>
		<label for="dafile"><h4>Upload Book</h4></label> <%= file_field_tag "dafile" %>
		<%= submit_tag "Upload"%>
		<% end %>
	</div>
</div>

<div class="content">
	<div id="drop-files" ondragover="return false">
		Drop Images Here
	</div>

	<div id="uploaded-holder">
		<div id="dropped-files">
			<div id="upload-button">
				<a href="#" class="upload">Upload!</a>
				<a href="#" class="delete">delete</a>
				<span>0 Files</span>
			</div>
		</div>
		<div id="extra-files">
			<div class="number">
				0
			</div>
			<div id="file-list">
				<ul></ul>
			</div>
		</div>
	</div>

	<div id="loading">
		<div id="loading-bar">
			<div class="loading-color"></div>
		</div>
		<div id="loading-content">
			Uploading file.jpg
		</div>
	</div>

	<div id="file-name-holder">
		<ul id="uploaded-files">
			<h1>Uploaded Books</h1>
		</ul>
	</div>
</div>

app/views/books/myaccount.html.erb
<div class="center_content">
	<div class="left_content">
		<%= form_tag '/uploads/uploadfile',:multipart => true do %>
		<label for="dafile"><h4>Upload Book</h4></label> <%= file_field_tag "dafile" %>
		<%= submit_tag "Upload"%>
		<% end %>
	</div>
</div>

<div class="content">
	<div id="drop-files" ondragover="return false">
		Drop Images Here
	</div>

	<div id="uploaded-holder">
		<div id="dropped-files">
			<div id="upload-button">
				<a href="#" class="upload">Upload!</a>
				<a href="#" class="delete">delete</a>
				<span>0 Files</span>
			</div>
		</div>
		<div id="extra-files">
			<div class="number">
				0
			</div>
			<div id="file-list">
				<ul></ul>
			</div>
		</div>
	</div>

	<div id="loading">
		<div id="loading-bar">
			<div class="loading-color"></div>
		</div>
		<div id="loading-content">
			Uploading file.jpg
		</div>
	</div>

	<div id="file-name-holder">
		<ul id="uploaded-files">
			<h1>Uploaded Books</h1>
		</ul>
	</div>
</div>

app/views/books/new.html.erb
<div class="center_content">

	<div class="left_content">

		<div class="title">
			<span class="title_icon"> <img src="/assets/bullet1.gif" alt="" title="" /> </span>
			<%= link_to "Most Downloaded", books_category_path %>

		</div>

		<div class="feat_prod_box">

			<div class="prod_img">
				<p>
					<img src="/assets/rrr.jpg" alt="" title="click to more details" border="0" />
				</p>
			</div>

			<div class="prod_det_box">
				<div class="box_top"></div>
				<div class="box_center">
					<div class="prod_title">
						<a href="">The Book of Ruby</a>
					</div>
					<p class="details">
						
						In this book, it is my aim to guide you safely
						over the pitfalls and lead you
						through the choppy waters of Ruby’s syntax and class libraries.
						In the process, I’ll be exploring both the smooth, well-paved highways
						and the gnarlier,bumpy little byways of Ruby.
					
					</p>

					<div class="clear"></div>
				</div>

				<div class="box_bottom"></div>
			</div>
			<div class="clear"></div>
		</div>

		<div class="feat_prod_box">

			<div class="prod_img">
				<p>
					<img src="/assets/cs.jpg" alt="" title="click to more details" border="0" />
				</p>
			</div>

			<div class="prod_det_box">
				<div class="box_top"></div>
				<div class="box_center">
					<div class="prod_title">
<<<<<<< HEAD
						
=======
						<a href="">The Book of CSS 3</a>
>>>>>>> e5dce8d37db448d88e1c003f4007fa5ca3a46c20
					</div>
					<p class="details">
						The Book of CSS3 helps you leverage the
						excellent knowledge you have of
						CSS2.1 in order to make learning CSS3 easier.

					</p>

					<div class="clear"></div>
				</div>
				<div class="box_bottom"></div>
			</div>
			<div class="clear"></div>
		</div>

		<div class="title">
			<span class="title_icon"> <img src="/assets/bullet2.gif" alt="" title="" /> </span><%= link_to "Most Recent", books_boks_path %>
		</div>

		<div class="new_products">

			<div class="new_prod_box">
<<<<<<< HEAD


=======
				<a href="">Web development</a>
				
>>>>>>> e5dce8d37db448d88e1c003f4007fa5ca3a46c20
				<div class="new_prod_bg">
					<span class="new_icon"> <img src="/assets/new_icon.gif" alt="" title="" /></span>
					 <img src="/assets/al.jpg" alt="" title="" class="thumb" border="0" /> 
				</div>
			</div>

			<div class="new_prod_box">
<<<<<<< HEAD
				
=======
				<a href="">Beginning CSS</a>
>>>>>>> e5dce8d37db448d88e1c003f4007fa5ca3a46c20
				<div class="new_prod_bg">
					<span class="new_icon"> <img src="/assets/new_icon.gif" alt="" title="" /></span>
					 <img src="/assets/gth.jpg" alt="" title="" class="thumb" border="0" /> </a>
				</div>
			</div>

			<div class="new_prod_box">
<<<<<<< HEAD
				
=======
				<a href="">JS for web Developers</a>
>>>>>>> e5dce8d37db448d88e1c003f4007fa5ca3a46c20
				<div class="new_prod_bg">
					<span class="new_icon"> <img src="/assets/new_icon.gif" alt="" title="" /></span>
				<img src="/assets/jaa.jpg" alt="" title="" class="thumb" border="0" /> </a>
				</div>
			</div>

			<div class="new_prod_box">
<<<<<<< HEAD
				
=======
			<a href="">Ruby on Rails 3</a>
>>>>>>> e5dce8d37db448d88e1c003f4007fa5ca3a46c20
				<div class="new_prod_bg">
					<span class="new_icon"> <img src="/assets/new_icon.gif" alt="" title="" /></span>
				 <img src="/assets/oh.jpg" alt="" title="" class="thumb" border="0" /> </a>
				</div>
			</div>

			<div class="new_prod_box">
<<<<<<< HEAD
				
=======
				<a href="">JS for web Apps</a>
>>>>>>> e5dce8d37db448d88e1c003f4007fa5ca3a46c20
				<div class="new_prod_bg">
					<span class="new_icon"> <img src="/assets/new_icon.gif" alt="" title="" /></span>
					 <img src="/assets/pr.jpg" alt="" title="" class="thumb" border="0" /> </a>
				</div>
			</div>

			<div class="new_prod_box">
<<<<<<< HEAD
				
=======
				<a href="">The Complete reference</a>
>>>>>>> e5dce8d37db448d88e1c003f4007fa5ca3a46c20
				<div class="new_prod_bg">
					<span class="new_icon"> <img src="/assets/new_icon.gif" alt="" title="" /></span>
					 <img src="/assets/uk.jpg" alt="" title="" class="thumb" border="0" /> </a>
				</div>

			</div>

		</div>

		<div class="clear"></div>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>

		<meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
		<title>Books Kreatio</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<div id="wrap">

			<div class="header">
				<div class="logo">

					<img src="/assets/logo.gif" alt="" title="" border="0" />
				</div>
				<div id="menu">
					<ul>
						<li>
							<%= link_to "Home", books_new_path%>
						</li>
						<li>
							<%= link_to "About us", books_about_path%>
						</li>
						<li>
							<%= link_to "Books", books_boks_path%>
						</li>
						<li>
							<%= link_to "Category", books_category_path%>
						</li>
						<li>
							<%= link_to "My Account", books_my_account_path%>
						</li>
						<li>
							<%= link_to "Contact", books_contact_path%>
						</li>
					</ul>
				</div>
			</div>

			<div class="center_content">
				<div class="left_content">
					<%= yield %>
				</div><!--end of left content-->
				<div class="right_content">

					<%= form_tag books_find_path, :method => :get do %>
					<p>
						<%= text_field_tag :search, params[:search] %>
						<%= submit_tag "Search", :name => nil %>
					</p>
					<% end %>

					<p style="color: green">
						<%= flash[:notice] %>
					</p>

					<div class="cart">
						
					</div>

					<div class="title">
						<span class="title_icon"> <img src="/assets/bullet3.gif" alt="" title="" /></span>About Our Store
					</div>
					
					<div class="about">

						<img src="/assets/about.gif" alt="" title="" class="right" />
						<p>
							BookStore.net is a super quick and simple search engine for books that helps
							you find the price and availability of books across various online bookstores.
							It also provides user store reviews, which further help users to choose
							the best deal on the right store.
						</p>

					</div>

					<div class="right_box">

						<div class="title">
							<span class="title_icon"><img src="/assets/bullet4.gif" alt="" title="" /> </span>Related Books
						</div>

						<div class="new_prod_box">

							<div class="new_prod_bg">
								<span class="new_icon"> </span>

								<img src="/assets/xm.jpg" alt="" title="" class="thumb" border="0" />
								</a>
							</div>
						</div>

						<div class="new_prod_box">
							
							<div class="new_prod_bg">
								<span class="new_icon"> </span>

								<img src="/assets/gi.jpg" alt="" title="" class="thumb" border="0" />
								</a>
							</div>
						</div>

					</div>

					<div class="right_box">

						<div class="title">
							<span class="title_icon"><img src="/assets/bullet5.gif" alt="" title="" /> </span>Categories
						</div>

						<ul class="list">
							<li>
								<%= link_to "Ruby", books_category_path%>
							</li>
							<li>
								<%= link_to "Rails", books_category_path%>
							</li>
							<li>
								<%= link_to "CSS", books_category_path%>
							</li>
							<li>
								<%= link_to "JavaScript", books_category_path%>
							</li>
							<li>
								<%= link_to "XML", books_category_path%>
							</li>
							<li>
								<%= link_to "AJAX", books_category_path%>
							</li>
							<li>
								<%= link_to "HTML", books_category_path%>
							</li>
							<li>
								<%= link_to "Database", books_category_path%>
							</li>
							<li>
								<%= link_to "Ubuntu", books_category_path%>
							</li>

						</ul>

						<div class="title">
							<span class="title_icon"></span>
						</div>

					</div>

				</div>

				<div class="clear"></div>
			</div><!--end of center content-->

			<div class="footer">
				<div class="left_footer">
					<a href="http://www.kreatio.com" target="_blank"> <img src="/assets/kr.jpg" alt="" title="" border="0" /> </a>
					<img src="/assets/footer_logo.gif" alt="" title="" />
				</div>
				<div class="right_footer">

					<%= link_to "home", books_new_path%>
					<%= link_to "about us", books_about_path%>
					<%= link_to "services", books_boks_path%>
					<%= link_to "privacy policy", books_my_account_path%>
					<%= link_to "Contact", books_contact_path%>

				</div>

			</div>

		</div>

	</body>
</html>